### PR TITLE
Added option to start the image in "fullscreen"

### PR DESCRIPTION
**Pull request by hcarneiro**
screen shot 2018-06-20 at 15 03 10

screen shot 2018-06-20 at 15 03 47

### CODE REVIEW

**Comment by tonytlwu** [comment]
@hcarneiro 

image 2018-06-20 at 3 14 43 pm

image 2018-06-20 at 3 12 33 pm

**Comment by hcarneiro** [comment]
**UI changes**

screen shot 2018-06-20 at 15 34 18

screen shot 2018-06-20 at 15 34 24

screen shot 2018-06-20 at 15 34 35

**Comment by benws1** [comment]
@twu - the correct solution would be to show the image full screen rather than explain in text what it would be.  Hugo explained to me that he couldn't do this because of the way the widget editor has been built? so for me the answer is to ask you to update the widget editor (specifically - the issue is making the image position fixed collapses the parent widget wrapper so it's not clickable - I'm sure you can work out a way to make it clickable still. Hugo and I have discussed some solutions.)

**Comment by tonytlwu** [comment]
@benws1 The answer would be to ask me to update the widget editor if that was the problem. As far as I know @hcarneiro and I didn't discuss the widget editor being the problem. If there was, I'd be happy to point @hcarneiro in the right direction.

We did discuss a separate issue with a potential scenario such as below:

1. User drops in several components on the page. Let's say we've dropped enough components to make a difference in load time because each component would have its own script to execute.
2. User drops in an image component and chooses to make it full screen & fixed for pinch-to-zoom.
3. The image component appears full screen, hence blocking the cursor access to all other components.
4. App user sees only one image component on the page, but in fact all the other components are still on the screen, and cannot be deleted by app editors because they're not accessible by the cursor.

**Comment by benws1** [comment]
@twu - the issue is that there is a visual layout disconnect between the edit page and the preview page. Has this been fixed?

**Pull request merged**
