### PR TITLE
Rebuild and UI improvements

### PR DESCRIPTION
**Pull request by hcarneiro**

### CODE REVIEW

**Comment by seromenho** [comment]
@hcarneiro 
Can I suggest we remove the current content when open a folder?
That way we wouldn't have anything behind the loader?

**Comment by hcarneiro** [comment]
@seromenho I'm going to note down that suggestion and maybe add it in later. I don't want tiny changes like that to hold off the work.

**Comment by seromenho** [comment]
@hcarneiro 
Typo when one file is selected 
https://cl.ly/2E322x2F1U0c

Also, this suggest to me that I should be able to select more than one file

**Comment by hcarneiro** [comment]
@seromenho I agree with your recommendation. Removed the "X files selected" message because as you pointed out it looks you can select more and in this widget you can't.

**Pull request merged**
